version: 1.0.0
main: me.rockyhawk.naturalpanels.NaturalPanels
name: NaturalPanels
author: RockyHawk
api-version: '1.13'
folia-supported: true
description: Fully Custom Dialog GUIs. Make your Server Professional.
softdepend: [PlaceholderAPI, Vault, TokenManager, VotingPlugin, floodgate]
commands:
  naturalpanels:
    description: Main plugin command.
    usage: /naturalpanels <command> [arguments]
    aliases: [np]
permissions:
  naturalpanels.command:
    default: true
  naturalpanels.reload:
    default: op
  naturalpanels.open:
    default: true