version: 0.0.1-ALPHA
main: me.rockyhawk.naturalpanels.NaturalPanels
name: NaturalPanels
author: RockyHawk
api-version: '1.13'
folia-supported: true
description: Fully Custom Dialog GUIs. Make your Server Professional.
softdepend: [PlaceholderAPI, Vault, floodgate]
commands:
  naturalpanels:
    description: Main plugin command.
    usage: /naturalpanels <command> [arguments]
    aliases: [np]
permissions:
  naturalpanels.command:
    default: true
  naturalpanels.command.reload:
    default: op
  naturalpanels.command.version:
    default: true
  naturalpanels.command.open:
    default: true
  naturalpanels.command.help:
    default: true